name = "HeuristicBVPSolve"
uuid = "bf23e988-fdb1-43ea-8178-ae1be000a8a2"
authors = ["Grant Hecht"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
